### ISSUE TITLE
Use panels in every *:show template

### ISSUE THREAD

**Issue by sourcerer-mike** [sourcerer-mike/crmp#9]
bs3-panel:table or :primary

- [x] PanelPass
- [x] Templating / Rendering in template
- [x] Templating as option
- [x] Method to hook in singular panels
- [x] Refactor bundles / entities
  - [x] CrmBundle
  - [x] AcquisitionBundle
  - [x] AccountingBundle

**Comment by sourcerer-mike** [comment]
http://getbootstrap.com/components/#panels

**Comment by klein0r** [comment]
+1

**Comment by sourcerer-mike** [comment]
Hat nur fünf Tage gedauert @klein0r ;D
